server:
  port: 8080
spring:
  h2:
    console:
      path: /h2-console
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver  # Database? H2? ?????.
    url: jdbc:h2:~/test  # H2 ?? ??
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
